= Map vSphere Features to OpenShift Virtualization
:navtitle: Home
// Title must be in Uppercase, hence changed the word - feature

Welcome to this quick course, _Map vSphere Features to OpenShift Virtualization_.
This quick course is a part of a series of courses about Migrate Applications and VM workloads from VMware to OpenShift Virtualization.

== Authors

The PTL team acknowledges the valuable contributions of the following Red Hat associates:

* Andrew Sullivan
* Ken Savich
* Laura Thain
* Sarvesh Pandit

== Prerequisites

For this course, you should have:

* RHCSA or higher is helpful for the navigation and usage of the command line, but it is not required.
* https://developers.redhat.com/learn/rhel/container-fundamentals[Container Fundamentals]
* https://developers.redhat.com/learn/openshift/foundations-openshift[Foundations of OpenShift]

== Objectives

The overall objectives of this course include:

* Identify features and capabilities of Red Hat OpenShift Virtualization that are equivalent to VMware vSphere one
* Map the features and capabilities of VMware vSphere to OpenShift Virtualization